import { useEffect, useState } from 'react';
import type { CSSProperties } from 'react';
import { useNavigate, useParams } from 'react-router';
import { Archive, Beaker, CheckCircle2, Copy, Eye, FlaskConical, PackageCheck, Play, Plus, RotateCcw, Save, Trash2 } from 'lucide-react';
import { toast } from 'sonner';

import { DynamicTableRenderer, type ColumnDef } from '../../../shared/components/DynamicTableRenderer';
import { ModuleStateView } from '../../../shared/components/ModuleStateView';
import { usePermission } from '../../../shared/hooks/usePermission';
import { getApiErrorMessage } from '../../../services/apiClient';
import { getItems as getCatalogItems } from '../../../services/catalogService';
import { inventoryService } from '../../../services/inventoryService';
import { metadataService } from '../../../services/metadataService';
import { recipeService } from '../../../services/recipeService';
import { unitManagementService } from '../../../services/unitManagementService';
import type { InventoryItem } from '../../../types/inventory';
import type { CatalogItem } from '../../../types/catalog';
import { RECIPE_PERMISSIONS, RECIPE_STATUS_CONFIG, RECIPE_TYPE_CONFIG, RECIPE_UOMS, type Recipe, type RecipeCalculationResult, type RecipeComponent, type RecipeExecution, type RecipeFilters, type RecipeOutput, type RecipePayload, type RecipeType, type RecipeVersion, type RecipeVersionPayload } from '../../../types/recipes';

type UnitOption = { id?: string | number; value?: string | number; name?: string; label?: string };
type MetaField = { key: string; label?: string; type?: string; field_type?: string; visible?: boolean; editable?: boolean; options?: Array<string | { label: string; value: string }> };

const pageStyle: CSSProperties = { padding: 24, background: '#F8FAFC', minHeight: '100%' };
const cardStyle: CSSProperties = { background: '#fff', border: '1px solid rgba(15,23,42,.08)', borderRadius: 8, padding: 18 };
const inputStyle: CSSProperties = { width: '100%', padding: '9px 11px', border: '1px solid #CBD5E1', borderRadius: 8, background: '#fff', color: '#0F172A', fontSize: 13, boxSizing: 'border-box' };
const muted = '#64748B';
const typeOptions: RecipeType[] = ['physical_product', 'service_consumption', 'operational_composition'];
const baseRecipeFields = new Set(['code', 'name', 'description', 'recipe_type', 'catalog_item_id', 'active', 'metadata']);
const baseVersionFields = new Set(['effective_from', 'effective_until', 'base_quantity', 'base_uom_id', 'expected_yield_quantity', 'expected_yield_uom_id', 'expected_waste_percent', 'metadata']);

function Header({ title, subtitle, actions }: { title: string; subtitle: string; actions?: React.ReactNode }) {
  return <div style={{ display: 'flex', justifyContent: 'space-between', gap: 15, flexWrap: 'wrap', marginBottom: 20 }}><div style={{ display: 'flex', gap: 12, alignItems: 'center' }}><div style={{ width: 44, height: 44, borderRadius: 8, display: 'grid', placeItems: 'center', background: '#0F766E', color: '#fff' }}><FlaskConical size={21} /></div><div><h1 style={{ margin: 0, fontSize: 22, color: '#0F172A' }}>{title}</h1><p style={{ margin: '4px 0 0', color: muted, fontSize: 13 }}>{subtitle}</p></div></div>{actions && <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>{actions}</div>}</div>;
}

function Button({ children, onClick, secondary, danger, disabled, testId }: { children: React.ReactNode; onClick: () => void; secondary?: boolean; danger?: boolean; disabled?: boolean; testId?: string }) {
  const color = danger ? '#DC2626' : secondary ? '#334155' : '#fff';
  const background = disabled ? '#CBD5E1' : danger ? '#FEF2F2' : secondary ? '#fff' : '#0F766E';
  return <button data-testid={testId} type="button" onClick={onClick} disabled={disabled} style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '9px 13px', borderRadius: 8, border: secondary || danger ? '1px solid #E2E8F0' : 0, background, color, fontWeight: 700, fontSize: 13, cursor: disabled ? 'not-allowed' : 'pointer' }}>{children}</button>;
}

function Badge({ label, color, bg }: { label: string; color: string; bg: string }) {
  return <span style={{ display: 'inline-flex', borderRadius: 999, padding: '4px 9px', fontSize: 12, fontWeight: 700, color, background: bg }}>{label}</span>;
}

function uomById(id?: number | string | null) { return RECIPE_UOMS.find(item => item.id === Number(id)) ?? RECIPE_UOMS[0]; }
function money(value: string | number | null | undefined) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value ?? 0)); }
function numberText(value: string | number | null | undefined) { return new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 6 }).format(Number(value ?? 0)); }
function dateValue(value?: string | null) { return value ? value.slice(0, 10) : ''; }
function optionId(option: UnitOption) { return String(option.id ?? option.value ?? ''); }
function optionLabel(option: UnitOption) { return option.label ?? option.name ?? String(option.value ?? option.id ?? 'Unidade'); }
function newComponent(order: number, item?: InventoryItem): RecipeComponent { const uom = RECIPE_UOMS.find(row => row.code === item?.unitOfMeasure) ?? RECIPE_UOMS[0]; return { inventory_item_id: item?.id ?? '', quantity: 1, uom_id: uom.id, expected_waste_percent: null, optional: false, sort_order: order, metadata: {} }; }
function newOutput(item?: InventoryItem): RecipeOutput { const uom = RECIPE_UOMS.find(row => row.code === item?.unitOfMeasure) ?? RECIPE_UOMS[0]; return { output_type: 'inventory_item', inventory_item_id: item?.id ?? null, catalog_item_id: null, description: '', quantity: 1, uom_id: uom.id, is_primary: true, metadata: {} }; }
function CustomMetadataFields({ fields, values, onChange }: { fields: MetaField[]; values: Record<string, unknown>; onChange: (values: Record<string, unknown>) => void }) {
  const visible = fields.filter(field => field.visible !== false && field.editable !== false);
  if (!visible.length) return null;
  return <div style={{ ...cardStyle, marginTop: 14 }}><h3 style={{ marginTop: 0, fontSize: 15 }}>Metadados</h3><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 10 }}>{visible.map(field => {
    const type = field.type ?? field.field_type ?? 'text';
    const label = field.label ?? field.key;
    if (type === 'select') {
      const options = (field.options ?? []).map(option => typeof option === 'string' ? { label: option, value: option } : option);
      return <label key={field.key}>{label}<select style={inputStyle} value={String(values[field.key] ?? '')} onChange={event => onChange({ ...values, [field.key]: event.target.value })}><option value="">Selecione</option>{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>;
    }
    if (type === 'boolean' || type === 'checkbox') return <label key={field.key} style={{ display: 'flex', gap: 8, alignItems: 'center', paddingTop: 24 }}><input type="checkbox" checked={Boolean(values[field.key])} onChange={event => onChange({ ...values, [field.key]: event.target.checked })} /> {label}</label>;
    return <label key={field.key}>{label}<input style={inputStyle} type={type === 'number' ? 'number' : 'text'} value={String(values[field.key] ?? '')} onChange={event => onChange({ ...values, [field.key]: type === 'number' ? Number(event.target.value) : event.target.value })} /></label>;
  })}</div></div>;
}

function VersionSummary({ version }: { version?: RecipeVersion | null }) {
  if (!version) return <span style={{ color: muted }}>Sem versao publicada</span>;
  const status = RECIPE_STATUS_CONFIG[version.status] ?? RECIPE_STATUS_CONFIG.draft;
  return <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}><strong>v{version.version}</strong><Badge label={status.label} color={status.color} bg={status.bg} /><span style={{ color: muted }}>{numberText(version.expected_yield_quantity)} {version.expected_yield_uom?.symbol ?? uomById(version.expected_yield_uom_id).symbol}</span></div>;
}

export function RecipesListPage() {
  const navigate = useNavigate();
  const { hasPermission } = usePermission();
  const [rows, setRows] = useState<Recipe[]>([]);
  const [filters, setFilters] = useState<RecipeFilters>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { setRows((await recipeService.list(filters)).data); } catch { setError('Nao foi possivel carregar as fichas tecnicas.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(() => void load(), 180); return () => clearTimeout(timer); }, [JSON.stringify(filters)]);
  const archive = async (recipe: Recipe) => { if (!window.confirm(`Arquivar ${recipe.name}?`)) return; try { await recipeService.archive(String(recipe.id)); toast.success('Ficha arquivada.'); await load(); } catch (error) { toast.error(getApiErrorMessage(error, 'Nao foi possivel arquivar.')); } };
  const columns: ColumnDef[] = [
    { key: 'code', label: 'Codigo', width: '120px', render: value => <strong style={{ fontFamily: 'monospace', color: '#0F766E' }}>{String(value)}</strong> },
    { key: 'name', label: 'Ficha tecnica' },
    { key: 'recipe_type', label: 'Tipo', width: '180px', render: value => { const cfg = RECIPE_TYPE_CONFIG[value as RecipeType] ?? RECIPE_TYPE_CONFIG.operational_composition; return <Badge label={cfg.label} color={cfg.color} bg={cfg.bg} />; } },
    { key: 'catalog_item', label: 'Item de catalogo', width: '180px', render: value => (value as Recipe['catalog_item'])?.name ?? '-' },
    { key: 'active_version', label: 'Versao oficial', width: '220px', render: value => <VersionSummary version={value as RecipeVersion | null} /> },
    { key: 'active', label: 'Status', width: '110px', render: value => value ? <Badge label="Ativa" color="#047857" bg="#D1FAE5" /> : <Badge label="Arquivada" color="#991B1B" bg="#FEE2E2" /> },
  ];
  if (error && !rows.length) return <ModuleStateView state="error" errorMessage={error} onRetry={() => void load()} />;
  return <div style={pageStyle} data-testid="recipes-page"><Header title="Fichas Tecnicas" subtitle="Composicoes versionadas da rede, sem execucao fisica de estoque nesta tela." actions={hasPermission(RECIPE_PERMISSIONS.create) ? <Button onClick={() => navigate('/recipes/new')} testId="recipe-new-button"><Plus size={14} /> Nova ficha</Button> : undefined} />
    <div style={{ ...cardStyle, padding: 12, display: 'grid', gridTemplateColumns: 'minmax(220px,2fr) minmax(150px,1fr) minmax(130px,1fr)', gap: 8, marginBottom: 14 }}><input data-testid="recipe-search" style={inputStyle} placeholder="Buscar por codigo ou nome" value={filters.search ?? ''} onChange={event => setFilters(current => ({ ...current, search: event.target.value }))} /><select style={inputStyle} value={filters.recipe_type ?? ''} onChange={event => setFilters(current => ({ ...current, recipe_type: event.target.value as RecipeType | '' }))}><option value="">Todos os tipos</option>{typeOptions.map(type => <option key={type} value={type}>{RECIPE_TYPE_CONFIG[type].label}</option>)}</select><select style={inputStyle} value={filters.active === '' || filters.active === undefined ? '' : String(filters.active)} onChange={event => setFilters(current => ({ ...current, active: event.target.value === '' ? '' : event.target.value === 'true' }))}><option value="">Todas</option><option value="true">Ativas</option><option value="false">Arquivadas</option></select></div>
    <DynamicTableRenderer columns={columns} data={rows as unknown as Record<string, unknown>[]} loading={loading} emptyMessage="Nenhuma ficha tecnica encontrada." actions={[{ label: 'Ver', icon: <Eye size={13} />, onClick: row => navigate(`/recipes/${row.id}`) }, { label: 'Arquivar', icon: <Archive size={13} />, variant: 'danger', showCondition: row => Boolean(row.active) && hasPermission(RECIPE_PERMISSIONS.archive), onClick: row => void archive(row as unknown as Recipe) }]} />
  </div>;
}
export function RecipeCreatePage() {
  const navigate = useNavigate();
  const [catalogItems, setCatalogItems] = useState<CatalogItem[]>([]);
  const [metadataFields, setMetadataFields] = useState<MetaField[]>([]);
  const [form, setForm] = useState<RecipePayload>({ code: '', name: '', description: '', recipe_type: 'physical_product', catalog_item_id: null, active: true, metadata: {}, create_initial_version: true, version: { base_quantity: 1, base_uom_id: 1, expected_yield_quantity: 1, expected_yield_uom_id: 1 } });
  const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([getCatalogItems({ status: 'active' }).catch(() => [] as CatalogItem[]), metadataService.getEntity('recipes').catch(() => null)]).then(([catalog, metadata]) => { setCatalogItems(catalog); setMetadataFields(((metadata?.form_schema ?? []) as MetaField[]).filter(field => !baseRecipeFields.has(field.key))); }); }, []);
  const save = async () => { if (!form.code.trim() || !form.name.trim()) { toast.error('Informe codigo e nome da ficha.'); return; } setSaving(true); try { const recipe = await recipeService.create({ ...form, catalog_item_id: form.catalog_item_id || null }); toast.success('Ficha criada.'); const versions = await recipeService.versions(String(recipe.id)).catch(() => []); const draft = versions[0] ?? recipe.active_version; navigate(draft ? `/recipes/${recipe.id}/versions/${draft.version}` : `/recipes/${recipe.id}`); } catch (error) { toast.error(getApiErrorMessage(error, 'Nao foi possivel criar a ficha.')); } finally { setSaving(false); } };
  return <div style={pageStyle} data-testid="recipe-create-page"><Header title="Nova ficha tecnica" subtitle="Crie a identidade da composicao. O primeiro rascunho sera aberto em seguida." actions={<><Button secondary onClick={() => navigate('/recipes')}>Cancelar</Button><Button disabled={saving} onClick={() => void save()} testId="recipe-save-button"><Save size={14} /> Criar ficha</Button></>} />
    <div style={{ ...cardStyle, maxWidth: 980 }}><h3 style={{ marginTop: 0 }}>Identidade</h3><div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 12 }}><label>Codigo<input data-testid="recipe-code" style={inputStyle} value={form.code} onChange={event => setForm(current => ({ ...current, code: event.target.value }))} /></label><label>Nome<input data-testid="recipe-name" style={inputStyle} value={form.name} onChange={event => setForm(current => ({ ...current, name: event.target.value }))} /></label><label>Tipo<select data-testid="recipe-type" style={inputStyle} value={form.recipe_type} onChange={event => setForm(current => ({ ...current, recipe_type: event.target.value as RecipeType }))}>{typeOptions.map(type => <option key={type} value={type}>{RECIPE_TYPE_CONFIG[type].label}</option>)}</select></label><label>Item de catalogo<select style={inputStyle} value={String(form.catalog_item_id ?? '')} onChange={event => setForm(current => ({ ...current, catalog_item_id: event.target.value || null }))}><option value="">Sem vinculo</option>{catalogItems.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label style={{ gridColumn: '1 / -1' }}>Descricao<textarea style={{ ...inputStyle, minHeight: 86 }} value={form.description ?? ''} onChange={event => setForm(current => ({ ...current, description: event.target.value }))} /></label><label style={{ display: 'flex', alignItems: 'center', gap: 8 }}><input type="checkbox" checked={form.active !== false} onChange={event => setForm(current => ({ ...current, active: event.target.checked }))} /> Ativa</label></div></div>
    <CustomMetadataFields fields={metadataFields} values={form.metadata ?? {}} onChange={values => setForm(current => ({ ...current, metadata: values }))} />
  </div>;
}

export function RecipeDetailPage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const { hasPermission } = usePermission();
  const [recipe, setRecipe] = useState<Recipe | null>(null); const [versions, setVersions] = useState<RecipeVersion[]>([]); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const [nextRecipe, nextVersions] = await Promise.all([recipeService.get(id), recipeService.versions(id)]); setRecipe(nextRecipe); setVersions(nextVersions); } catch { toast.error('Ficha tecnica nao encontrada.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [id]);
  const clone = async (version: RecipeVersion) => { try { const draft = await recipeService.cloneVersion(id, String(version.version)); toast.success('Nova versao em rascunho criada.'); navigate(`/recipes/${id}/versions/${draft.version}`); } catch (error) { toast.error(getApiErrorMessage(error, 'Nao foi possivel clonar a versao.')); } };
  if (loading) return <ModuleStateView state="loading" />;
  if (!recipe) return <ModuleStateView state="error" errorMessage="Ficha tecnica nao encontrada." />;
  const type = RECIPE_TYPE_CONFIG[recipe.recipe_type];
  return <div style={pageStyle} data-testid="recipe-detail-page"><Header title={recipe.name} subtitle={`${recipe.code} | ${type.label}`} actions={<><Button secondary onClick={() => navigate('/recipes')}>Voltar</Button>{hasPermission(RECIPE_PERMISSIONS.update) && <Button onClick={() => navigate(`/recipes/${recipe.id}/versions/${versions[0]?.version ?? 1}`)}><Beaker size={14} /> Editar versao</Button>}</>} />
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 340px', gap: 16 }}><section style={cardStyle}><h3 style={{ marginTop: 0 }}>Resumo</h3><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 12 }}><div><small style={{ color: muted }}>Tipo</small><div><Badge label={type.label} color={type.color} bg={type.bg} /></div></div><div><small style={{ color: muted }}>Catalogo</small><strong style={{ display: 'block' }}>{recipe.catalog_item?.name ?? '-'}</strong></div><div><small style={{ color: muted }}>Versao oficial</small><VersionSummary version={recipe.active_version} /></div></div>{recipe.description && <p style={{ marginBottom: 0, color: '#334155' }}>{recipe.description}</p>}</section><aside style={cardStyle}><h3 style={{ marginTop: 0 }}>Limites da fase</h3><p style={{ color: muted, lineHeight: 1.55 }}>Esta tela configura composicao e calcula previa oficial. Nao executa producao, nao baixa estoque e nao gera Financeiro/DRE.</p></aside></div>
    <section style={{ ...cardStyle, marginTop: 16 }}><h3 style={{ marginTop: 0 }}>Versoes</h3><div data-testid="recipe-versions-list" style={{ display: 'grid', gap: 8 }}>{versions.map(item => { const status = RECIPE_STATUS_CONFIG[item.status] ?? RECIPE_STATUS_CONFIG.draft; return <div key={item.id} style={{ display: 'grid', gridTemplateColumns: '90px 140px 1fr auto', alignItems: 'center', gap: 10, padding: 10, border: '1px solid #E2E8F0', borderRadius: 8 }}><strong>v{item.version}</strong><Badge label={status.label} color={status.color} bg={status.bg} /><span style={{ color: muted }}>{item.components.length} componentes | {item.outputs.length} saida(s)</span><div style={{ display: 'flex', gap: 6 }}><Button secondary onClick={() => navigate(`/recipes/${id}/versions/${item.version}`)}><Eye size={13} /> Abrir</Button>{item.status !== 'draft' && hasPermission(RECIPE_PERMISSIONS.update) && <Button secondary onClick={() => void clone(item)}><Copy size={13} /> Clonar</Button>}</div></div>; })}</div></section>
  </div>;
}
export function RecipeVersionEditorPage() {
  const { id = '', version: versionParam = '1' } = useParams(); const navigate = useNavigate(); const { hasPermission } = usePermission();
  const [recipe, setRecipe] = useState<Recipe | null>(null); const [version, setVersion] = useState<RecipeVersion | null>(null); const [items, setItems] = useState<InventoryItem[]>([]); const [catalogItems, setCatalogItems] = useState<CatalogItem[]>([]); const [units, setUnits] = useState<UnitOption[]>([]); const [metadataFields, setMetadataFields] = useState<MetaField[]>([]);
  const [form, setForm] = useState<RecipeVersionPayload>({ base_quantity: 1, base_uom_id: 1, expected_yield_quantity: 1, expected_yield_uom_id: 1, expected_waste_percent: null, components: [], outputs: [] });
  const [calculation, setCalculation] = useState<RecipeCalculationResult | null>(null); const [preview, setPreview] = useState({ quantity: 1, uomId: 1, unitId: '' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const [nextRecipe, nextVersion, inventoryItems, catalog, unitOptions, metadata] = await Promise.all([recipeService.get(id), recipeService.getVersion(id, versionParam), inventoryService.listItems({ active: true }), getCatalogItems({ status: 'active' }).catch(() => [] as CatalogItem[]), unitManagementService.getUnitOptions().catch(() => [] as UnitOption[]), metadataService.getEntity('recipe_versions').catch(() => null)]); setRecipe(nextRecipe); setVersion(nextVersion); setItems(inventoryItems); setCatalogItems(catalog); setUnits(unitOptions); setMetadataFields(((metadata?.form_schema ?? []) as MetaField[]).filter(field => !baseVersionFields.has(field.key))); setForm({ effective_from: dateValue(nextVersion.effective_from), effective_until: dateValue(nextVersion.effective_until), base_quantity: nextVersion.base_quantity, base_uom_id: nextVersion.base_uom_id, expected_yield_quantity: nextVersion.expected_yield_quantity, expected_yield_uom_id: nextVersion.expected_yield_uom_id, expected_waste_percent: nextVersion.expected_waste_percent, governance: nextVersion.governance, settings: nextVersion.settings, metadata: nextVersion.metadata, components: nextVersion.components, outputs: nextVersion.outputs }); setPreview({ quantity: nextVersion.expected_yield_quantity || 1, uomId: nextVersion.expected_yield_uom_id || 1, unitId: '' }); } catch { toast.error('Nao foi possivel carregar a versao.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [id, versionParam]);
  const editable = version?.status === 'draft' && hasPermission(RECIPE_PERMISSIONS.update); const components = form.components ?? []; const outputs = form.outputs ?? []; const primaryOutput = outputs[0] ?? null;
  const patchComponent = (index: number, patch: Partial<RecipeComponent>) => setForm(current => ({ ...current, components: components.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row) }));
  const patchOutput = (patch: Partial<RecipeOutput>) => setForm(current => ({ ...current, outputs: [{ ...(primaryOutput ?? newOutput()), ...patch, is_primary: true }] }));
  const save = async () => { if (!editable || !version) return; if (!components.length) { toast.error('Adicione ao menos um componente.'); return; } if (recipe?.recipe_type === 'physical_product' && (!primaryOutput || (!primaryOutput.inventory_item_id && !primaryOutput.catalog_item_id))) { toast.error('Produto fisico exige uma saida principal.'); return; } setSaving(true); try { const saved = await recipeService.updateVersion(id, String(version.version), form); setVersion(saved); setForm(current => ({ ...current, components: saved.components, outputs: saved.outputs })); toast.success('Versao salva.'); } catch (error) { toast.error(getApiErrorMessage(error, 'Nao foi possivel salvar a versao.')); } finally { setSaving(false); } };
  const validate = async () => { if (!version) return; try { await recipeService.validateVersion(id, String(version.version)); toast.success('Versao valida para publicacao.'); } catch (error) { toast.error(getApiErrorMessage(error, 'A versao ainda nao pode ser publicada.')); } };
  const publish = async () => { if (!version || !window.confirm('Publicar esta versao? Ela ficara imutavel e sera usada como ficha oficial.')) return; try { const published = await recipeService.publishVersion(id, String(version.version)); toast.success('Versao publicada.'); setVersion(published); await load(); } catch (error) { toast.error(getApiErrorMessage(error, 'Nao foi possivel publicar.')); } };
  const clone = async () => { if (!version) return; try { const draft = await recipeService.cloneVersion(id, String(version.version)); toast.success('Nova versao em rascunho criada.'); navigate(`/recipes/${id}/versions/${draft.version}`); } catch (error) { toast.error(getApiErrorMessage(error, 'Nao foi possivel clonar a versao.')); } };
  const calculate = async () => { if (!version || version.status !== 'published') { toast.info('Publique a versao para calcular uma previa oficial.'); return; } try { setCalculation(await recipeService.calculate(id, String(version.version), { target_quantity: preview.quantity, target_uom_id: preview.uomId, unit_id: preview.unitId || null })); } catch (error) { toast.error(getApiErrorMessage(error, 'Nao foi possivel calcular a composicao.')); } };
  if (loading) return <ModuleStateView state="loading" />; if (!recipe || !version) return <ModuleStateView state="error" errorMessage="Versao nao encontrada." />; const status = RECIPE_STATUS_CONFIG[version.status] ?? RECIPE_STATUS_CONFIG.draft;
  return <div style={pageStyle} data-testid="recipe-version-editor"><Header title={`${recipe.name} - v${version.version}`} subtitle="Edicao simples de rendimento, componentes e saida principal." actions={<><Button secondary onClick={() => navigate(`/recipes/${id}`)}>Voltar</Button>{editable && <Button disabled={saving} onClick={() => void save()} testId="recipe-version-save"><Save size={14} /> Salvar</Button>}<Button secondary onClick={() => void validate()} testId="recipe-version-validate"><CheckCircle2 size={14} /> Validar</Button>{editable && hasPermission(RECIPE_PERMISSIONS.publish) && <Button onClick={() => void publish()} testId="recipe-version-publish"><PackageCheck size={14} /> Publicar</Button>}{!editable && hasPermission(RECIPE_PERMISSIONS.update) && <Button secondary onClick={() => void clone()}><Copy size={14} /> Clonar</Button>}</>} />
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 380px', gap: 16, alignItems: 'start' }}><main style={{ display: 'grid', gap: 14 }}>
      <section style={cardStyle}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12 }}><h3 style={{ margin: 0 }}>Dados da versao</h3><Badge label={status.label} color={status.color} bg={status.bg} /></div><fieldset disabled={!editable} style={{ border: 0, padding: 0, margin: 0 }}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,minmax(0,1fr))', gap: 10 }}><label>Rendimento<input data-testid="recipe-yield" type="number" min="0.001" step="0.001" style={inputStyle} value={form.expected_yield_quantity} onChange={event => setForm(current => ({ ...current, expected_yield_quantity: Number(event.target.value) }))} /></label><label>UOM rendimento<select style={inputStyle} value={form.expected_yield_uom_id} onChange={event => setForm(current => ({ ...current, expected_yield_uom_id: Number(event.target.value), base_uom_id: Number(event.target.value) }))}>{RECIPE_UOMS.map(uom => <option key={uom.id} value={uom.id}>{uom.name} ({uom.symbol})</option>)}</select></label><label>Perda global %<input type="number" min="0" max="100" step="0.01" style={inputStyle} value={form.expected_waste_percent ?? ''} onChange={event => setForm(current => ({ ...current, expected_waste_percent: event.target.value === '' ? null : Number(event.target.value) }))} /></label><label>Vigencia inicial<input type="date" style={inputStyle} value={form.effective_from ?? ''} onChange={event => setForm(current => ({ ...current, effective_from: event.target.value || null }))} /></label></div></fieldset></section>
      <section style={cardStyle}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12 }}><h3 style={{ margin: 0 }}>Componentes</h3>{editable && <Button onClick={() => setForm(current => ({ ...current, components: [...components, newComponent(components.length + 1)] }))} testId="recipe-add-component"><Plus size={13} /> Componente</Button>}</div><div style={{ display: 'grid', gap: 8 }} data-testid="recipe-components-table">{components.map((component, index) => <div key={`${component.id ?? 'new'}-${index}`} style={{ display: 'grid', gridTemplateColumns: '1.5fr .55fr .75fr .65fr .55fr auto', gap: 8, alignItems: 'end' }}><label>Item<select disabled={!editable} data-testid={`recipe-component-item-${index}`} style={inputStyle} value={String(component.inventory_item_id ?? '')} onChange={event => { const item = items.find(row => row.id === event.target.value); patchComponent(index, { inventory_item_id: event.target.value, uom_id: (RECIPE_UOMS.find(uom => uom.code === item?.unitOfMeasure) ?? uomById(component.uom_id)).id }); }}><option value="">Selecione</option>{items.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Qtd.<input disabled={!editable} type="number" min="0.001" step="0.001" style={inputStyle} value={component.quantity} onChange={event => patchComponent(index, { quantity: Number(event.target.value) })} /></label><label>UOM<select disabled={!editable} style={inputStyle} value={component.uom_id} onChange={event => patchComponent(index, { uom_id: Number(event.target.value) })}>{RECIPE_UOMS.map(uom => <option key={uom.id} value={uom.id}>{uom.symbol}</option>)}</select></label><label>Perda %<input disabled={!editable} type="number" min="0" max="100" step="0.01" style={inputStyle} value={component.expected_waste_percent ?? ''} onChange={event => patchComponent(index, { expected_waste_percent: event.target.value === '' ? null : Number(event.target.value) })} /></label><label style={{ display: 'flex', gap: 6, alignItems: 'center', paddingBottom: 9 }}><input disabled={!editable} type="checkbox" checked={Boolean(component.optional)} onChange={event => patchComponent(index, { optional: event.target.checked })} /> Opc.</label>{editable && <button type="button" title="Remover" onClick={() => setForm(current => ({ ...current, components: components.filter((_, rowIndex) => rowIndex !== index).map((row, rowIndex) => ({ ...row, sort_order: rowIndex + 1 })) }))} style={{ border: 0, background: '#FEF2F2', color: '#DC2626', borderRadius: 8, padding: 9 }}><Trash2 size={14} /></button>}</div>)}</div></section>
      <section style={cardStyle}><h3 style={{ marginTop: 0 }}>Saida principal</h3><fieldset disabled={!editable} style={{ border: 0, padding: 0, margin: 0 }}><div style={{ display: 'grid', gridTemplateColumns: '1fr 1.2fr .55fr .7fr', gap: 10 }}><label>Tipo<select data-testid="recipe-output-type" style={inputStyle} value={primaryOutput?.output_type ?? 'inventory_item'} onChange={event => patchOutput({ output_type: event.target.value, inventory_item_id: null, catalog_item_id: null })}><option value="inventory_item">InventoryItem</option><option value="catalog_item">CatalogItem</option><option value="service_result">Resultado de servico</option><option value="waste">Perda</option></select></label>{(primaryOutput?.output_type ?? 'inventory_item') === 'catalog_item' ? <label>Catalogo<select style={inputStyle} value={String(primaryOutput?.catalog_item_id ?? '')} onChange={event => patchOutput({ catalog_item_id: event.target.value || null })}><option value="">Selecione</option>{catalogItems.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : (primaryOutput?.output_type ?? 'inventory_item') === 'inventory_item' ? <label>Item produzido<select data-testid="recipe-output-item" style={inputStyle} value={String(primaryOutput?.inventory_item_id ?? '')} onChange={event => { const item = items.find(row => row.id === event.target.value); patchOutput({ inventory_item_id: event.target.value || null, uom_id: (RECIPE_UOMS.find(uom => uom.code === item?.unitOfMeasure) ?? uomById(primaryOutput?.uom_id)).id }); }}><option value="">Selecione</option>{items.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : <label>Descricao<input style={inputStyle} value={primaryOutput?.description ?? ''} onChange={event => patchOutput({ description: event.target.value })} /></label>}<label>Qtd.<input type="number" min="0.001" step="0.001" style={inputStyle} value={primaryOutput?.quantity ?? form.expected_yield_quantity} onChange={event => patchOutput({ quantity: Number(event.target.value) })} /></label><label>UOM<select style={inputStyle} value={primaryOutput?.uom_id ?? form.expected_yield_uom_id} onChange={event => patchOutput({ uom_id: Number(event.target.value) })}>{RECIPE_UOMS.map(uom => <option key={uom.id} value={uom.id}>{uom.symbol}</option>)}</select></label></div></fieldset></section>
      <CustomMetadataFields fields={metadataFields} values={form.metadata ?? {}} onChange={values => setForm(current => ({ ...current, metadata: values }))} />
    </main><aside style={{ display: 'grid', gap: 14 }}><section style={cardStyle} data-testid="recipe-preview-panel"><h3 style={{ marginTop: 0 }}>Previa automatica</h3>{version.status !== 'published' ? <p style={{ color: muted, lineHeight: 1.55 }}>Publique a versao para calcular uma previa oficial. O frontend nao duplica a regra de calculo localmente.</p> : <><div style={{ display: 'grid', gap: 9 }}><label>Quantidade alvo<input data-testid="recipe-preview-quantity" type="number" min="0.001" step="0.001" style={inputStyle} value={preview.quantity} onChange={event => setPreview(current => ({ ...current, quantity: Number(event.target.value) }))} /></label><label>Unidade alvo<select style={inputStyle} value={preview.uomId} onChange={event => setPreview(current => ({ ...current, uomId: Number(event.target.value) }))}>{RECIPE_UOMS.map(uom => <option key={uom.id} value={uom.id}>{uom.name}</option>)}</select></label><label>Unidade operacional<select style={inputStyle} value={preview.unitId} onChange={event => setPreview(current => ({ ...current, unitId: event.target.value }))}><option value="">Sem custo local</option>{units.map(unit => <option key={optionId(unit)} value={optionId(unit)}>{optionLabel(unit)}</option>)}</select></label><Button onClick={() => void calculate()} testId="recipe-calculate-button"><Beaker size={14} /> Calcular</Button></div>{calculation && <div data-testid="recipe-calculation-result" style={{ marginTop: 14 }}><p style={{ margin: '8px 0' }}>Custo estimado <strong style={{ float: 'right', color: '#047857' }}>{money(calculation.estimated_total_cost)}</strong></p><p style={{ margin: '8px 0' }}>Custo por unidade <strong style={{ float: 'right' }}>{calculation.estimated_cost_per_output_unit ? money(calculation.estimated_cost_per_output_unit) : '-'}</strong></p><hr /><strong>Componentes</strong><div style={{ display: 'grid', gap: 8, marginTop: 8 }}>{calculation.components.map(component => <div key={component.id} style={{ display: 'flex', justifyContent: 'space-between', gap: 10, fontSize: 13 }}><span>{component.name}</span><strong>{numberText(component.gross_quantity)} {component.uom.symbol}</strong></div>)}</div>{calculation.warnings.length > 0 && <div style={{ marginTop: 12, padding: 10, background: '#FFFBEB', borderRadius: 8, color: '#92400E' }}>{calculation.warnings.map((warning, index) => <p key={`${warning.code}-${index}`} style={{ margin: index ? '6px 0 0' : 0 }}>{warning.message ?? warning.code}</p>)}</div>}</div>}</>}</section><section style={cardStyle}><h3 style={{ marginTop: 0 }}>Contrato operacional</h3><p style={{ color: muted, lineHeight: 1.55, marginBottom: 0 }}>Salvar, validar, publicar e calcular nao criam StockMovement, nao alteram StockBalance e nao geram Financeiro.</p></section></aside></div>
  </div>;
}

export function RecipeExecutionsListPage() {
  const navigate = useNavigate();
  const { hasPermission } = usePermission();
  const [rows, setRows] = useState<RecipeExecution[]>([]);
  const [loading, setLoading] = useState(true);
  const [status, setStatus] = useState('');
  const load = async () => {
    setLoading(true);
    try { setRows((await recipeService.listExecutions({ status })).data); } catch { toast.error('Nao foi possivel carregar as execucoes.'); } finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [status]);
  const columns: ColumnDef[] = [
    { key: 'number', label: 'Numero', width: '150px', render: value => <strong style={{ fontFamily: 'monospace', color: '#0F766E' }}>{String(value)}</strong> },
    { key: 'recipe', label: 'Ficha tecnica', render: value => (value as RecipeExecution['recipe'])?.name ?? '-' },
    { key: 'unit', label: 'Unidade', width: '170px', render: value => (value as RecipeExecution['unit'])?.name ?? '-' },
    { key: 'target_quantity', label: 'Quantidade', width: '140px', render: (_value, row) => `${numberText(row.target_quantity as number)} ${(row.target_uom as RecipeExecution['target_uom'])?.symbol ?? ''}` },
    { key: 'status', label: 'Status', width: '120px', render: value => value === 'reversed' ? <Badge label="Revertida" color="#991B1B" bg="#FEE2E2" /> : <Badge label="Confirmada" color="#047857" bg="#D1FAE5" /> },
    { key: 'executed_at', label: 'Data', width: '160px', render: value => value ? new Date(String(value)).toLocaleString('pt-BR') : '-' },
    { key: 'calculation_snapshot', label: 'Custo', width: '130px', render: value => money((value as RecipeCalculationResult)?.estimated_total_cost) },
  ];
  return <div style={pageStyle} data-testid="recipe-executions-page"><Header title="Producao e Consumo" subtitle="Execucoes manuais confirmadas a partir de fichas tecnicas publicadas." actions={hasPermission(RECIPE_PERMISSIONS.executionsCreate) ? <Button onClick={() => navigate('/recipe-executions/new')} testId="recipe-execution-new"><Play size={14} /> Executar ficha</Button> : undefined} />
    <div style={{ ...cardStyle, padding: 12, marginBottom: 14, maxWidth: 260 }}><select style={inputStyle} value={status} onChange={event => setStatus(event.target.value)}><option value="">Todos os status</option><option value="confirmed">Confirmadas</option><option value="reversed">Revertidas</option></select></div>
    <DynamicTableRenderer columns={columns} data={rows as unknown as Record<string, unknown>[]} loading={loading} emptyMessage="Nenhuma execucao registrada." actions={[{ label: 'Ver', icon: <Eye size={13} />, onClick: row => navigate(`/recipe-executions/${row.id}`) }]} />
  </div>;
}

export function RecipeExecutionCreatePage() {
  const navigate = useNavigate();
  const [recipes, setRecipes] = useState<Recipe[]>([]);
  const [units, setUnits] = useState<UnitOption[]>([]);
  const [locations, setLocations] = useState<Array<{ id: string; name: string; code?: string; unitId?: string }>>([]);
  const [form, setForm] = useState({ recipeId: '', unitId: '', locationId: '', quantity: 1, uomId: 1, notes: '' });
  const [calculation, setCalculation] = useState<RecipeCalculationResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([recipeService.list({ active: true }), unitManagementService.getUnitOptions().catch(() => [] as UnitOption[])]).then(([recipeList, unitOptions]) => { setRecipes(recipeList.data.filter(recipe => recipe.active_version?.status === 'published')); setUnits(unitOptions); }).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!form.unitId) { setLocations([]); return; } void inventoryService.listLocations({ unitId: form.unitId, active: true }).then(rows => setLocations(rows.map(row => ({ id: row.id, name: row.name, code: row.code, unitId: row.unitId ?? undefined })))).catch(() => setLocations([])); }, [form.unitId]);
  const selected = recipes.find(recipe => String(recipe.id) === form.recipeId);
  const activeVersion = selected?.active_version;
  useEffect(() => { if (activeVersion) setForm(current => ({ ...current, uomId: activeVersion.expected_yield_uom_id, quantity: activeVersion.expected_yield_quantity || 1 })); }, [activeVersion?.id]);
  const calculate = async () => {
    if (!selected || !activeVersion || !form.unitId) { toast.error('Selecione ficha tecnica e unidade.'); return; }
    try {
      setCalculation(await recipeService.calculate(String(selected.id), String(activeVersion.version), { target_quantity: form.quantity, target_uom_id: form.uomId, unit_id: form.unitId }));
    } catch (error) {
      setCalculation(null);
      toast.error(getApiErrorMessage(error, 'Nao foi possivel calcular a composicao.'));
    }
  };
  const confirm = async () => {
    if (!selected || !activeVersion || !calculation) { toast.error('Calcule e confira a composicao antes de confirmar.'); return; }
    if (!window.confirm('Esta acao movimentara o estoque. Confirmar execucao?')) return;
    setSaving(true);
    try {
      const execution = await recipeService.confirmExecution({ recipe_id: selected.id, recipe_version_id: activeVersion.id, unit_id: form.unitId, stock_location_id: form.locationId || null, target_quantity: form.quantity, target_uom_id: form.uomId, notes: form.notes });
      toast.success('Execucao confirmada e estoque movimentado.');
      navigate(`/recipe-executions/${execution.id}`);
    } catch (error) {
      toast.error(getApiErrorMessage(error, 'Nao foi possivel confirmar a execucao.'));
    } finally { setSaving(false); }
  };
  if (loading) return <ModuleStateView state="loading" />;
  return <div style={pageStyle} data-testid="recipe-execution-create-page"><Header title="Executar ficha tecnica" subtitle="Informe o que foi produzido ou realizado. O Orchestra calcula antes de movimentar o estoque." actions={<><Button secondary onClick={() => navigate('/recipe-executions')}>Cancelar</Button><Button disabled={saving || !calculation} onClick={() => void confirm()} testId="recipe-execution-confirm"><PackageCheck size={14} /> Confirmar execucao</Button></>} />
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,420px) minmax(0,1fr)', gap: 16, alignItems: 'start' }}>
      <section style={cardStyle}><h3 style={{ marginTop: 0 }}>Operacao</h3><div style={{ display: 'grid', gap: 10 }}><label>Ficha tecnica<select data-testid="execution-recipe" style={inputStyle} value={form.recipeId} onChange={event => { setCalculation(null); setForm(current => ({ ...current, recipeId: event.target.value })); }}><option value="">Selecione</option>{recipes.map(recipe => <option key={recipe.id} value={recipe.id}>{recipe.code} - {recipe.name}</option>)}</select></label><label>Unidade<select data-testid="execution-unit" style={inputStyle} value={form.unitId} onChange={event => { setCalculation(null); setForm(current => ({ ...current, unitId: event.target.value, locationId: '' })); }}><option value="">Selecione</option>{units.map(unit => <option key={optionId(unit)} value={optionId(unit)}>{optionLabel(unit)}</option>)}</select></label><label>Local<select data-testid="execution-location" style={inputStyle} value={form.locationId} onChange={event => setForm(current => ({ ...current, locationId: event.target.value }))}><option value="">Local default</option>{locations.map(location => <option key={location.id} value={location.id}>{location.name}{location.code ? ` (${location.code})` : ''}</option>)}</select></label><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}><label>Quantidade<input data-testid="execution-quantity" type="number" min="0.001" step="0.001" style={inputStyle} value={form.quantity} onChange={event => { setCalculation(null); setForm(current => ({ ...current, quantity: Number(event.target.value) })); }} /></label><label>UOM<select style={inputStyle} value={form.uomId} onChange={event => { setCalculation(null); setForm(current => ({ ...current, uomId: Number(event.target.value) })); }}>{RECIPE_UOMS.map(uom => <option key={uom.id} value={uom.id}>{uom.name}</option>)}</select></label></div><label>Observacao<textarea style={{ ...inputStyle, minHeight: 84 }} value={form.notes} onChange={event => setForm(current => ({ ...current, notes: event.target.value }))} /></label><Button onClick={() => void calculate()} testId="execution-calculate"><Beaker size={14} /> Calcular para conferencia</Button></div></section>
      <section style={cardStyle} data-testid="execution-review"><h3 style={{ marginTop: 0 }}>Conferencia</h3>{!calculation ? <p style={{ color: muted }}>Calcule a ficha para conferir consumo, entrada e custo estimado antes de confirmar.</p> : <div><p><strong>Producao:</strong> {numberText(calculation.expected_output.quantity)} {calculation.expected_output.uom.symbol} de {calculation.expected_output.description ?? selected?.name}</p><strong>Consumo</strong><div style={{ display: 'grid', gap: 8, marginTop: 8 }}>{calculation.components.map(component => <div key={component.id} style={{ display: 'flex', justifyContent: 'space-between', gap: 10 }}><span>{component.name}</span><strong>{numberText(component.gross_quantity)} {component.uom.symbol}</strong></div>)}</div>{calculation.expected_output.inventory_item_id && <p style={{ marginTop: 14 }}><strong>Entrada:</strong> {numberText(calculation.expected_output.quantity)} {calculation.expected_output.uom.symbol} de {calculation.expected_output.description}</p>}<p style={{ color: '#047857', fontWeight: 800 }}>Custo estimado: {money(calculation.estimated_total_cost)}</p>{calculation.warnings.length > 0 && <div style={{ marginTop: 12, padding: 10, borderRadius: 8, background: '#FFFBEB', color: '#92400E' }}>{calculation.warnings.map((warning, index) => <p key={`${warning.code}-${index}`} style={{ margin: index ? '6px 0 0' : 0 }}>{warning.message ?? warning.code}</p>)}</div>}<div style={{ marginTop: 14, padding: 10, borderRadius: 8, background: '#FEE2E2', color: '#991B1B', fontWeight: 700 }}>Esta acao movimentara o estoque.</div></div>}</section>
    </div>
  </div>;
}

export function RecipeExecutionDetailPage() {
  const { id = '' } = useParams();
  const navigate = useNavigate();
  const { hasPermission } = usePermission();
  const [execution, setExecution] = useState<RecipeExecution | null>(null);
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setExecution(await recipeService.getExecution(id)); } catch { toast.error('Execucao nao encontrada.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [id]);
  const reverse = async () => {
    const reason = window.prompt('Informe o motivo da reversao');
    if (!reason?.trim()) return;
    if (!window.confirm('A reversao criara movimentos compensatorios de estoque. Continuar?')) return;
    try { setExecution(await recipeService.reverseExecution(id, reason.trim())); toast.success('Execucao revertida.'); } catch (error) { toast.error(getApiErrorMessage(error, 'Nao foi possivel reverter a execucao.')); }
  };
  if (loading) return <ModuleStateView state="loading" />;
  if (!execution) return <ModuleStateView state="error" errorMessage="Execucao nao encontrada." />;
  const snapshot = execution.calculation_snapshot;
  return <div style={pageStyle} data-testid="recipe-execution-detail-page"><Header title={execution.number} subtitle={`${execution.recipe?.name ?? 'Ficha tecnica'} | ${execution.unit?.name ?? 'Unidade'}`} actions={<><Button secondary onClick={() => navigate('/recipe-executions')}>Voltar</Button>{execution.status === 'confirmed' && hasPermission(RECIPE_PERMISSIONS.executionsReverse) && <Button danger onClick={() => void reverse()} testId="recipe-execution-reverse"><RotateCcw size={14} /> Reverter</Button>}</>} />
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 360px', gap: 16, alignItems: 'start' }}><section style={cardStyle}><h3 style={{ marginTop: 0 }}>Snapshot da composicao</h3><p><strong>Quantidade:</strong> {numberText(execution.target_quantity)} {execution.target_uom?.symbol}</p><p><strong>Local:</strong> {execution.stock_location?.name}</p><p><strong>Status:</strong> {execution.status === 'reversed' ? 'Revertida' : 'Confirmada'}</p><strong>Componentes</strong><div style={{ display: 'grid', gap: 8, marginTop: 8 }}>{(snapshot.components ?? []).map(component => <div key={component.id} style={{ display: 'flex', justifyContent: 'space-between', gap: 10, padding: '8px 0', borderBottom: '1px solid #E2E8F0' }}><span>{component.name}</span><strong>{numberText(component.gross_quantity)} {component.uom.symbol}</strong></div>)}</div>{snapshot.expected_output && <p style={{ marginTop: 14 }}><strong>Output:</strong> {numberText(snapshot.expected_output.quantity)} {snapshot.expected_output.uom.symbol} de {snapshot.expected_output.description}</p>}<p style={{ color: '#047857', fontWeight: 800 }}>Custo estimado: {money(snapshot.estimated_total_cost)}</p></section><aside style={{ ...cardStyle, display: 'grid', gap: 8 }}><h3 style={{ marginTop: 0 }}>Movimentos vinculados</h3><p><strong>Saida:</strong> {execution.input_movement?.number ?? '-'}</p><p><strong>Entrada:</strong> {execution.output_movement?.number ?? 'Sem output fisico'}</p><p><strong>Operacao:</strong><br /><code>{execution.operation_id}</code></p><p><strong>Executado por:</strong> {execution.executed_by_name ?? '-'}</p>{execution.reversal_reason && <p><strong>Motivo da reversao:</strong> {execution.reversal_reason}</p>}</aside></div>
  </div>;
}
